---
- pause:
    minutes: 1

- include_tasks: ../../common/post_check.yml

- name: Show deployment status
  shell: cd "{{ tnm_crm_deployment_path }}" && ls -lrth
  register: result
- debug: msg="{{ result.stdout_lines }}"

- name: Show application status
  shell: ps -ef | grep -w "tnmCrm"
  register: tnm_cnm_status
- debug: msg="{{ tnm_cnm_status.stdout_lines }}"

- name: Check TNM-CRM APPLICATION running status
  shell: ps -ef | grep -w "tnmCrm" > /dev/null ; echo $?
  register: tnm_crm_status_check
- debug:
    msg: "TNM-CRM APPLICATION running"
  when: tnm_crm_status_check.stdout == "0"
- fail:
    msg: "TNM-CRM APPLICATION not running"
  when: tnm_crm_status_check.stdout != "0"

#- name: Show WFLYSRV0010 keyword in nohup.out file
#  shell: cat "{{ tnm_crm_log_path }}" | grep "WFLYSRV0010" | tail -1
#  register: result
#- debug: msg="{{ result.stdout_lines }}"

#- name: Check for WFLYSRV0010 keyword in nohup.out file
#  shell: cat "{{ tnm_crm_log_path }}" | grep "WFLYSRV0010" > /dev/null 2>&1 ; echo $?
#  register: result
#- debug:
#    msg: "WFLYSRV0010 successfully deployed"
#  when: result.stdout == "0"
#- fail:
#    msg: "WFLYSRV0010 not deployed successfully"
#  when: result.stdout != "0"
