---
- name: To check the MySQL status remote
  shell: |
    echo "mysqladmin -u{{ db_user }} -p{{ db_pass }} -h{{ db_host }} -P{{ db_port }} ping"
    mysqladmin -u{{ db_user }} -p{{ db_pass }} -h{{ db_host }} -P{{ db_port }} ping
  register: result
- debug: msg="{{result.stdout_lines}}"
- fail:
    msg: "MySQL is not running or inactive (dead)..."
  when: 'result.stdout is search("mysqld is alive") != true'
- debug:
    msg: "MySQL is active (running)..."
  when: 'result.stdout is search("mysqld is alive") == true'

