---
- name: Kill Process
  shell: |
    ps -aef | grep -w {{ process_name }} | grep -v grep 2>&1 > /dev/null
    if [ $? -eq 0 ]
    then
      echo "process {{ process_name }} is running"
      echo "killing the process {{ process_name }}" 
      ps -ef | grep {{ process_name }} | grep -v grep | awk '{print $2}'| xargs kill -9
      echo "{{ process_name }} process killed successfully" 
    else
      echo "No process is running with the name {{ process_name }}"
    fi
  register: result
- debug: msg="{{ result.stdout_lines }}"

- name: Check Process Status
  shell: |
    ps -aef | grep {{ process_name }}
  register: result
- debug: msg="{{ result.stdout_lines }}"