---
- name: Create BKP directory if not exists
  file:
    path: "{{ dir_path }}/BKP"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Taking DB backup
  shell: |
    # Cleaning old DB backup
    cd {{ dir_path }}/BKP
    mkdir temp
    mv {{ db_name }}_*.DUMP.sql temp

    # Taking DB backup
    mysqldump -u{{ db_user }} -p{{ db_pass_1 }} --no-data -h{{ db_host }} --databases {{ db_name }} > {{ dir_path }}/BKP/{{ db_name }}_$(date +"%d%m%Y%H%M%S")_DUMP.sql
    
    echo "DB Backup Path :"
    pwd
    ls -l
    echo "DB backup taken successfully..."
  register: result
- debug: msg="{{ result.stdout_lines }}"

- name: Removing Old DB backup
  shell: |
    cd {{ dir_path }}/BKP
    rm -rf temp
    echo "Removed Old DB backup successfully..."
  register: result
- debug: msg="{{ result.stdout_lines }}"