
---
- name: Fetching DB update script
  shell: |
    # Cleaning old DB script
    cd {{ dir_path }}
    rm -rf db_script*.sql

    #Downloading latest DB script
    cp -rf /home/tnmops/DEVOPS/db_script-{{ RELEASE_VERSION }}.sql ./
  register: result
- debug: msg="{{result.stdout_lines}}"

- name: Check the db_script.sql exists or not
  stat:
    path: "{{ dir_path }}/db_script-{{ RELEASE_VERSION }}.sql"
  register: result
- fail:
    msg: "{{ dir_path }}/db_script-{{ RELEASE_VERSION }}.sql not exists"
  when: result == False

- name: Executing DB script
  shell: |
    echo "mysql -u{{ db_user }} -p{{ db_pass }} -h{{ db_host }} -P{{ db_port }} -A {{ db_name }} < {{ dir_path }}/db_script-{{ RELEASE_VERSION }}.sql"
    mysql -u{{ db_user }} -p{{ db_pass }} -h{{ db_host }} -P{{ db_port }} -A {{ db_name }} < {{ dir_path }}/db_script-{{ RELEASE_VERSION }}.sql    
  register: result
- debug: msg="{{result.stdout_lines}}"
