---
- name: Restarting the application
  shell: |
    cd {{ com_app_startup_path }}
    nohup sh restart.sh > /dev/null 2>&1 &
    echo "Application started successfully..."
  register: result
- debug: msg="{{ result.stdout_lines }}"